version:     "01a-09-11-21"
copyright:   "2021-2021"
description:
  This is a
  GitHub Page for Operating Systems 212
disclaimer:
  I have spoken.
keywords:    "jekyll, testing"
navbarlinks:
- navbar:    "Home"
  link:      "/"
- navbar:    "Log"
  link:      "/TXT/mylog.txt"
- navbar:    "Links"
  link:      "/LINKS/"
- navbar:    "GitHub"
  link:      "https://github.com/ariiesaka/os212"
- navbar:    "About"
  link:      "/ABOUT/"
- navbar:    "GitHub Page"
  link:      "https://ariiesaka.github.io/os212/"
title:       "Operating Systems 212"
lang:        "en-US"
author:      "Judah A."
address:     "Indonesia"
sitemap:     "true"
markdown:    "kramdown"
defaults:
- scope:
    path:    ""
  values:
    layout:  "default"
github:
- metadata
plugins:
- jekyll-sitemap
- jekyll-seo-tag
google_analytics: "UA-89852122-15"

urlweb:           "https://ariiesaka.github.io/os212/"
urlcontact:       "TBA"
urlgithub:        "https://github.com/ariiesaka/os212"


